### ISSUE TITLE
AssertionError: Failed getting instance UID for series

### ISSUE THREAD

**Issue by sanjaykhobragade** [GoogleCloudPlatform/healthcare#118]
Script store_tcia_in_hc_api is throwing below error when running in datalab:

There are 2149 instances to upload...
Traceback (most recent call last):
  File "/usr/local/envs/py2env/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/envs/py2env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/content/datalab/healthcare/imaging/ml_codelab/scripts/store_tcia_in_hc_api.py", line 191, in <module>
    main()
  File "/content/datalab/healthcare/imaging/ml_codelab/scripts/store_tcia_in_hc_api.py", line 87, in main
    study_uid_to_series_uid.values()), 1):
  File "/usr/local/envs/py2env/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
AssertionError: Failed getting instance UID for series 1.3.6.1.4.1.9590.100.1.2.171166015912754582622813408142073790722

**Comment by sanjaykhobragade** [comment]
This is resolved. Issue was with my incorrect TCIA API Key.
