### ISSUE TITLE
Lung cancer training command error

### ISSUE THREAD

**Issue by tnhabib** [GoogleCloudPlatform/healthcare#336]
I am working through an exercise on qwiklabs

when I try to train the model via the command:
```
python3 -m models.trainer.model   --training_data=gs://${BUCKET?}/tfrecords/training.tfrecord   --eval_data=gs://${BUCKET?}/tfrecords/eval.tfrecord   --model_dir=gs://${BUCKET?}/model   --training_steps=3000   --eval_steps=1000   --learning_rate=0.1   --export_model_dir=gs://${BUCKET?}/saved_model
```

I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/google5577230_student/healthcare/fhir/lung-cancer/models/trainer/model.py", line 36, in <module>
    tf.flags.DEFINE_string(
AttributeError: module 'tensorflow' has no attribute 'flags'
```

**Comment by nikklassen** [comment]
Thank you for alerting us of your issue with this lab. The lab now contains instructions about installing the correct version of tensorflow.
