### ISSUE TITLE
Dataflow Preprocess step from breast_density_cloud_ml.ipynb notebook failing

### ISSUE THREAD

**Issue by sanjaykhobragade** [GoogleCloudPlatform/healthcare#406]
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead.
You are using pip version 9.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/local/envs/py2env/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/envs/py2env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/content/datalab/healthcare/imaging/ml_codelab/scripts/preprocess/preprocess.py", line 362, in <module>
    main(sys.argv[1:])
  File "/content/datalab/healthcare/imaging/ml_codelab/scripts/preprocess/preprocess.py", line 358, in main
    run(arg_dict)
  File "/content/datalab/healthcare/imaging/ml_codelab/scripts/preprocess/preprocess.py", line 275, in run
    configure_pipeline(p, in_args)
  File "/usr/local/envs/py2env/lib/python2.7/site-packages/apache_beam/pipeline.py", line 183, in __exit__
    self.run().wait_until_finish()
  File "/usr/local/envs/py2env/lib/python2.7/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 778, in wait_until_finish
    (self.state, getattr(self._runner, 'last_error_msg', None)), self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 581, in do_work
    work_executor.execute()
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/executor.py", line 166, in execute
    op.start()
  File "dataflow_worker/operations.py", line 283, in dataflow_worker.operations.DoOperation.start (dataflow_worker/operations.c:10680)
    def start(self):
  File "dataflow_worker/operations.py", line 284, in dataflow_worker.operations.DoOperation.start (dataflow_worker/operations.c:10574)
    with self.scoped_start_state:
  File "dataflow_worker/operations.py", line 321, in dataflow_worker.operations.DoOperation.start (dataflow_worker/operations.c:10521)
    self.dofn_runner.start()
  File "apache_beam/runners/common.py", line 408, in apache_beam.runners.common.DoFnRunner.start (apache_beam/runners/common.c:11132)
    self._invoke_bundle_method(self.do_fn_invoker.invoke_start_bundle)
  File "apache_beam/runners/common.py", line 402, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method (apache_beam/runners/common.c:10878)
    self._reraise_augmented(exn)
  File "apache_beam/runners/common.py", line 431, in apache_beam.runners.common.DoFnRunner._reraise_augmented (apache_beam/runners/common.c:11673)
    raise new_exn, None, original_traceback
  File "apache_beam/runners/common.py", line 400, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method (apache_beam/runners/common.c:10788)
    bundle_method()
  File "apache_beam/runners/common.py", line 168, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle (apache_beam/runners/common.c:5594)
    def invoke_start_bundle(self):
  File "apache_beam/runners/common.py", line 172, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle (apache_beam/runners/common.c:5489)
    self.signature.start_bundle_method.method_value())
  File "/content/datalab/healthcare/imaging/ml_codelab/scripts/preprocess/preprocess.py", line 162, in start_bundle
  File "/content/datalab/healthcare/imaging/ml_codelab/scripts/preprocess/preprocess.py", line 74, in __init__
  File "/content/datalab/healthcare/imaging/ml_codelab/scripts/preprocess/preprocess.py", line 94, in _build_graph
  File "/usr/local/lib/python2.7/dist-packages/scripts/ml_utils.py", line 21, in <module>
    import tensorflow_hub
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_hub/__init__.py", line 29, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_hub/estimator.py", line 25, in <module>
    from tensorflow_hub import tf_utils
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_hub/tf_utils.py", line 28, in <module>
    from tensorflow_hub import tf_v1
ImportError: cannot import name tf_v1 [while running 'Preprocess Image']

**Comment by codezizo** [comment]
@sanjaykhobragade there was an upgrade/update to the codelab which should resolve this. Please let me know if the latest version has a similar problem.

**Comment by codezizo** [comment]
Closing as this should no longer a be problem. Feel free to file a new bug if this is still occurring.
